# Generated by Django 4.1.3 on 2023-02-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('prazo', models.DateField(null=True)),
                ('periodicidade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Agendado', 'Agendado'), ('Concluida', 'Concluida')], default='Agendado', max_length=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Informações', models.TextField(blank=True, max_length=1000, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('Referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.maquina')),
            ],
        ),
    ]
