# Generated by Django 4.1.3 on 2022-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='cat_image/')),
            ],
        ),
        migrations.CreateModel(
            name='falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='cat_image/')),
            ],
        ),
        migrations.CreateModel(
            name='maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='regfail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=180)),
                ('description', models.TextField()),
            ],
        ),
    ]
