# Generated by Django 4.1.3 on 2022-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coberturatotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('NEO50s', 'NEO50s'), ('M75', 'M75'), ('IDEAPAD3i', 'IDEAPAD3i'), ('IDEAPAD3a', 'IDEAPAD3a'), ('IDEAPAD1', 'IDEAPAD1'), ('E14', 'E14')], max_length=30)),
                ('total_de_componentes', models.IntegerField()),
                ('total_testados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='compstatusn50S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='skip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('Detalhes', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='componente',
        ),
        migrations.DeleteModel(
            name='falha',
        ),
        migrations.DeleteModel(
            name='maquina',
        ),
    ]
