# Generated by Django 4.1.3 on 2022-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_coberturatotal_compstatusn50s_skip_delete_componente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='skiptest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('Máquina', models.CharField(max_length=10)),
                ('modelo', models.CharField(choices=[('NEO50s', 'NEO50s'), ('M75', 'M75'), ('IDEAPAD3i', 'IDEAPAD3i'), ('IDEAPAD3a', 'IDEAPAD3a'), ('IDEAPAD1', 'IDEAPAD1'), ('E14', 'E14')], max_length=30)),
                ('Detalhes', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='skip',
        ),
    ]
