# Generated by Django 4.1.3 on 2022-12-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_skiptest_delete_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiptest',
            name='status',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10),
        ),
    ]
