# Generated by Django 4.1.3 on 2022-12-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_skiptest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skiptest',
            new_name='skiptestn50s',
        ),
    ]
