# Generated by Django 4.1.3 on 2022-12-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_n50sict2_delete_skiptestn50s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n50sict2',
            old_name='Componente',
            new_name='component',
        ),
    ]
