# Generated by Django 4.1.3 on 2022-12-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_componente_n50sict2_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n50sict2',
            old_name='component',
            new_name='componente',
        ),
    ]
