# Generated by Django 4.1.3 on 2022-12-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_component_n50sict2_componente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n50sict2',
            name='modelo',
        ),
    ]
