# Generated by Django 4.1.3 on 2022-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_n50sict2_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='coberturatotaN50s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeds', models.IntegerField()),
                ('coverinplaceds', models.IntegerField()),
                ('testcover', models.IntegerField()),
                ('outcover', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='coberturatotal',
        ),
    ]
