# Generated by Django 4.1.3 on 2022-12-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_coberturatotan50s_delete_coberturatotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coberturatotan50s',
            old_name='coverinplaceds',
            new_name='testable',
        ),
        migrations.RenameField(
            model_name='coberturatotan50s',
            old_name='outcover',
            new_name='tested',
        ),
        migrations.RemoveField(
            model_name='coberturatotan50s',
            name='testcover',
        ),
    ]
