# Generated by Django 4.1.3 on 2022-12-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_coverinplaceds_coberturatotan50s_testable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coberturatotaN50s',
            new_name='coberturatotalN50s',
        ),
    ]
