# Generated by Django 4.1.3 on 2022-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_coberturatotan50s_coberturatotaln50s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compstatusn50S',
        ),
        migrations.AddField(
            model_name='coberturatotaln50s',
            name='boardname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
