# Generated by Django 4.1.3 on 2022-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_coberturatotal3i'),
    ]

    operations = [
        migrations.CreateModel(
            name='coberturatotalm75',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeds', models.IntegerField()),
                ('testable', models.IntegerField()),
                ('tested', models.IntegerField()),
                ('boardname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='m75ict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
    ]
