# Generated by Django 4.1.3 on 2022-12-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_coberturatotalm75_datetime_m75ict2'),
    ]

    operations = [
        migrations.CreateModel(
            name='coberturatotal3a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeds', models.IntegerField()),
                ('testable', models.IntegerField()),
                ('tested', models.IntegerField()),
                ('boardname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='coberturatotale14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeds', models.IntegerField()),
                ('testable', models.IntegerField()),
                ('tested', models.IntegerField()),
                ('boardname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='coberturatotalideapad1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeds', models.IntegerField()),
                ('testable', models.IntegerField()),
                ('tested', models.IntegerField()),
                ('boardname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='regfail',
        ),
    ]
