# Generated by Django 4.1.3 on 2022-12-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_coberturatotal3a_coberturatotale14_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='e14ict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='e14ict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad31ict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad31ict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3aict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3aict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3iict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3iict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='m75ict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='n50sict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('atualizado', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
            ],
        ),
    ]
