# Generated by Django 4.1.3 on 2022-12-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_e14ict1_e14ict2_ideapad31ict1_ideapad31ict2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e14ict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='e14ict2',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad31ict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad31ict2',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad3aict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad3aict2',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad3iict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='ideapad3iict2',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='m75ict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='m75ict2',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='n50sict1',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='n50sict2',
            name='atualizado',
        ),
    ]
