# Generated by Django 4.1.3 on 2022-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_e14ict1_atualizado_remove_e14ict2_atualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e14ict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='e14ict2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad31ict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad31ict2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad3aict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad3aict2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad3iict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ideapad3iict2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='m75ict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='m75ict2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='n50sict1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='n50sict2',
            name='status',
        ),
    ]
