# Generated by Django 4.1.3 on 2022-12-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_e14ict1_status_remove_e14ict2_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='e14ict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad31ict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3aict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ideapad3iict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='m75ict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='n50sict3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=30)),
                ('Falha', models.CharField(choices=[('preshort', 'preshort'), ('short', 'short'), ('analog', 'analog'), ('vectorless', 'vectorless')], max_length=30)),
                ('Motivo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
